// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"myproject/project/handler"
	"myproject/project/repository"
	"myproject/project/routes"
	"myproject/project/service"
)

// Injectors from wire.go:

func CreateUserConfig() (*routes.UserConfigRoutes, error) {
	userConfigRepository := repository.NewUserConfigRepository()
	userConfigService := service.NewUserConfigService(userConfigRepository)
	userConfigHandler := handler.NewUserConfigHandler(userConfigService)
	userConfigRoutes := routes.NewUserConfigRoutes(userConfigHandler)
	return userConfigRoutes, nil
}
